---
Description: Set up an Amazon Linux web server
Parameters:
  KeyName:
    Description: The Name of the existing EC2 keypair to enable ssh access to the instance
    Type: AWS::EC2::KeyPair::KeyName
  SSHCIDR: 
    Type: String
    Description: The CIDR block restricting SSH
    MinLength: 9
    Default: 131.247.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x 
  
Mappings: 
  Region2AMI:
    us-east-1: 
      AMI: ami-09d069a04349dc3cb
    us-west-1:
      AMI: ami-0fc20dd1da406780b
Resources: 
  EC2Instance: 
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files: 
            /var/www/html/index.html:
              content: !
                <title> Dharani Manian </title>
                <h1> Dharani Manian cloud formed server</h1>
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
                
    Properties:
      ImageId: !FindInMap [Region2AMI, !Ref 'AWS::Region', 'AMI']
      InstanceType: t2.micro
      SecurityGroups: 
      - !Ref WebServerSecurityGroup
      Tags:
      - Key: Name
        Value: amazon linux server
      KeyName: !Ref KeyName
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -x
          yum update -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
          
        
  
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP
      SecurityGroupIngress: 
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        ToPort: 80
        IpProtocol: tcp
      - CidrIp: !Ref SSHCIDR
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
Outputs:
  WebURL:
    Description: The URL for the web page.
    Value: !Sub 'http://${EC2Instance.PublicIp}'
  PublicDNS: 
    Description: The AWS public DNS for the instance 
    Value: !Sub '${EC2Instance.PublicDnsName}'
  Region:
    Description: The Region.
    Value: !Ref 'AWS::Region'
