---
Description: Set up an Ubuntu nginx web server
Parameters:
  KeyName:
    Description: The Name of the existing EC2 keypair to enable ssh access to the instance
    Type: AWS::EC2::KeyPair::KeyName
  SSHCIDR: 
    Type: String
    Description: The CIDR block restricting SSH
    MinLength: 9
    Default: 131.247.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x 
  
Mappings: 
  Region2AMI:
    us-east-1: 
      AMI: ami-07ebfd5b3428b6f4d
    us-east-2:
      AMI: ami-0fc20dd1da406780b
Resources: 
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [Region2AMI, !Ref 'AWS::Region', 'AMI']
      InstanceType: t2.micro
      SecurityGroups: 
      - !Ref WebServerSecurityGroup
      Tags:
      - Key: Name
        Value: Ubuntu nginx server
      KeyName: !Ref KeyName
      UserData:
        'Fn::Base64': |
          #!/bin/bash -x
          
          #set timezone
          timedatectl set-timezone America/New_York
          
          #install and set up nginx
          sudo apt-get update -y
          TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
          && curl -H "X-aws-ec2-metadata-token: $TOKEN" –v http://169.254.169.254/latest/meta-data/public-ipv4
          sudo apt-get update -y 
          sudo apt-get install -y nginx
          cd /var/www/html
          echo "<title> Dharani Manian </title>" > index.html
          echo "<h1> Dharani Manian </h1>" >> index.html
        
  
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP
      SecurityGroupIngress: 
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        ToPort: 80
        IpProtocol: tcp
      - CidrIp: !Ref SSHCIDR
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
Outputs:
  WebURL:
    Description: The URL for the web page.
    Value: !Sub 'http://${EC2Instance.PublicIp}'
  PublicDNS: 
    Description: The AWS public DNS for the instance 
    Value: !Sub '${EC2Instance.PublicDnsName}'
  Region:
    Description: The Region.
    Value: !Ref 'AWS::Region'
