---
Description: Set up an Ubuntu nginx web server
Parameters:
  KeyName:
    Description: The Name of the existing EC2 keypair to enable ssh access to the instance
    Type: AWS::EC2::KeyPair::KeyName
  SSHCIDR: 
    Type: String
    Description: The CIDR block restricting SSH
    MinLength: 9
    Default: 131.247.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x 
Resources: 
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07ebfd5b3428b6f4d
      InstanceType: t2.micro
      SecurityGroups: 
      - !Ref WebServerSecurityGroup
      Tags:
      - Key: Name
        Value: Ubuntu nginx server
      KeyName: !Ref KeyName
      UserData:
        'Fn::Base64': |
          #!/bin/bash -x
          
          #set timezone
          timedatectl set-timezone America/New_York
          
          #install and set up nginx
          sudo apt-get update -y 
          sudo apt-get install -y nginx
          
          #write title and header to index.html
          cd /var/www/html
          echo "<title> Dharani Manian </title>" > index.html
          echo "<h1> Dharani Manian </h1>" >> index.html
          echo "<p> Public DNS : </p>" >> index.html
          
          #write public DNS to index.html
          curl http://169.254.169.254/latest/meta-data/public-hostname >> index.html
          echo "<p> </p>" >> index.html
          
          #write Region to index.html
          curl http://169.254.169.254/latest/dynamic/instance-identity/document >> temp.txt
          echo $(grep region temp.txt) | tr '",' '  ' >> index.html
        
  
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP
      SecurityGroupIngress: 
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        ToPort: 80
        IpProtocol: tcp
      - CidrIp: !Ref SSHCIDR
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
Outputs:
  WebURL:
    Description: The URL for the web page.
    Value: !Sub 'http://${EC2Instance.PublicIp}'
